### ISSUE TITLE
uninitialized constant VerboseMigrations::MigrationExtension (NameError) with ruby 3.2.4 and Rails 7

### ISSUE THREAD

**Issue by compwron** [keygen-sh/verbose_migrations#1]
Error on running `rake db:migrate` after adding verbose_migrations to gemfile and running a new migration

```
/Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/verbose_migrations-1.0.0/lib/verbose_migrations/railtie.rb:5:in `block in <module:VerboseMigrations>': uninitialized constant VerboseMigrations::MigrationExtension (NameError)
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/lazy_load_hooks.rb:95:in `class_eval'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/lazy_load_hooks.rb:95:in `block in execute_hook'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/lazy_load_hooks.rb:60:in `block in on_load'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/lazy_load_hooks.rb:59:in `each'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8.4/lib/active_support/lazy_load_hooks.rb:59:in `on_load'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/verbose_migrations-1.0.0/lib/verbose_migrations/railtie.rb:4:in `<module:VerboseMigrations>'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/verbose_migrations-1.0.0/lib/verbose_migrations/railtie.rb:3:in `<main>'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/verbose_migrations-1.0.0/lib/verbose_migrations.rb:8:in `require_relative'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/verbose_migrations-1.0.0/lib/verbose_migrations.rb:8:in `<main>'
	from <internal:/Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/runtime.rb:55:in `each'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/runtime.rb:44:in `each'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/runtime.rb:44:in `require'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler.rb:187:in `require'
	from /Users/me/ph/app-workflow/config/application.rb:21:in `<top (required)>'
	from <internal:/Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/spring-4.2.1/lib/spring/application.rb:97:in `preload'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/spring-4.2.1/lib/spring/application.rb:171:in `serve'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/spring-4.2.1/lib/spring/application.rb:153:in `block in run'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/spring-4.2.1/lib/spring/application.rb:147:in `loop'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/spring-4.2.1/lib/spring/application.rb:147:in `run'
	from /Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/gems/3.2.0/gems/spring-4.2.1/lib/spring/application/boot.rb:25:in `<top (required)>'
	from <internal:/Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/Users/me/.asdf/installs/ruby/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from -e:1:in `<main>'
```

new migration:
```
class AddTableFoo < ActiveRecord::Migration[6.1]
  verbose!

  def change
    create_table :foo do |t|
      t.string :external_id, null: false, index: { unique: true }
      t.jsonb :raw_data

      t.timestamps
    end
  end
end
```

**Comment by ezekg** [comment]
Hmm, sorry about that. Seems like a loading issue since the module is defined [here](https://github.com/keygen-sh/verbose_migrations/blob/master/lib/verbose_migrations.rb#L11). Give me a few hours and I'll dig in and figure out what's going on here.

**Comment by ezekg** [comment]
Should be fixed in 3e6fe3c95379b992dc3ede6a83208c1beae2fb12. Could you try using master and lmk?

```rb
gem 'verbose_migrations', git: 'https://github.com/keygen-sh/verbose_migrations', branch: 'master'
```

I'll cut a new release after we confirm it's fixed.

**Comment by ezekg** [comment]
I tested myself and this seems to resolve the issue. Cut release v1.0.1. I'll reopen if the issue persists.

**Comment by compwron** [comment]
Very cool, thanks!
